### PR TITLE
contact page edited

### PR DESCRIPTION
**Pull request by abhijain2003**
contact page edited please merge it under hacktoberfest 2022
Screenshot 2022-10-11 085751

### CODE REVIEW

**Comment by abhijain2003** [comment]
hey will you please merge it under hacktoberfest 2022

**Comment by abhinavkashyap061** [comment]
hey @abhijain2003 the current contact page doesn't require any changes. add facebook link in it https://www.facebook.com/abhinavkashyap061 and i will merge it in for hacktoberfest 2022

**Review by abhinavkashyap061 — CHANGES_REQUESTED** [review]
don't change the HTML elements as it will create errors/UI bugs . just add Facebook icon following the same order of other links and I will merge it.

**Comment by abhijain2003** [comment]
sure and sorry for this

**Comment by abhinavkashyap061** [comment]
you can fetch the remote branch and checkout, maybe try that or create a new issue no problem

**Comment by abhijain2003** [comment]
I tried this one also and it create same issues

let me tell what i did

first i forked the repo
then i made changes
then I use git remote add upstream https://github.com/abhinavkashyap061/Dear-Diary.git 
then I user git remote -v
git pull upstream main
then i created new branch
added changes
commit changes
and push changes remotely


and now today I made new changes, and simply run the command 
git add .
git commit -m "----"
git push -u <branch>

and it throws errors to me

please help me

**Comment by abhijain2003** [comment]
I am getting error's like this

**Comment by abhijain2003** [comment]
hey, can you help on this please

**Comment by abhijain2003** [comment]
bro please help on this

**Pull request closed without merging**
